FROM ubuntu:20.04
LABEL Creator: "juanpgarza"

RUN apt-get update \
    && apt-get upgrade -y

RUN apt-get install -y \
    openssh-server fail2ban

RUN adduser --disabled-password --gecos "Odoo" odoo

RUN apt-get install -y \
    python3-pip

RUN apt-get install -y python-dev python3-dev libxml2-dev libxslt1-dev zlib1g-dev libsasl2-dev libldap2-dev build-essential libssl-dev libffi-dev libmysqlclient-dev libjpeg-dev libpq-dev libjpeg8-dev liblcms2-dev libblas-dev libatlas-base-dev

WORKDIR /opt/odoo

COPY src/requirements.txt .

RUN pip3 install -r requirements.txt

RUN apt-get update \
    && \
    apt-get install -y \
    nano

RUN pip3 install pyopenssl

RUN wget https://github.com/wkhtmltopdf/wkhtmltopdf/releases/download/0.12.5/wkhtmltox_0.12.5-1.bionic_amd64.deb

RUN apt install -y ./wkhtmltox_0.12.5-1.bionic_amd64.deb

####### Cliente postgres
RUN apt update && apt install -y curl ca-certificates gnupg2

RUN curl https://www.postgresql.org/media/keys/ACCC4CF8.asc | apt-key add -

RUN echo "deb http://apt.postgresql.org/pub/repos/apt/ bionic-pgdg main" > /etc/apt/sources.list.d/pgdg.list

RUN apt-get update && apt-get install -y postgresql-client-12
#######################

######## open-upgrade
RUN apt-get install git -y

RUN pip3 install git+https://github.com/OCA/openupgradelib/@master

######## click-odoo
RUN pip3 install click-odoo

RUN echo "export PYTHONPATH=/opt/odoo" >> ~/.bashrc

RUN pip3 install click-odoo-contrib

########
RUN apt-get update && apt install -y python3-unidecode